### ISSUE TITLE
A new test about a car that had been sold

### ISSUE THREAD

**Issue by staskikotx** [srapisarda/stypes#2]
New test about a car being sold from the DL-17 paper.

Tests ternary relations.

The files are ont-car.dlp, Q-car.cq and Q-car.gml

**Comment by srapisarda** [comment]
small fix with revision number f72a0f6bae33dbf01b4539ef4cba6eef81a0fc4a

**Comment by srapisarda** [comment]
Ontology:
purchase(X,Y,Z) :- purchased(X,Y).
sale(Z,Y,X) :- purchase(X,Y,Z).

Query:
q():-car(Y),sale(X,Y,Z).

Rewriting produced:
p1() :- purchased(Z,Y), car(Y).
p1() :- car(Y), sale(X,Y,Z).
